export const VerificationTokenRequest = {
    REGISTRATION: 'REGISTRATION',
    EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
    LOGIN: 'LOGIN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD'
}

export const documentTypes = {
    PHOTO: 'PHOTO',
    PAN_CARD: 'PAN_CARD',
    AADHAR_CARD: 'AADHAR_CARD',
    OTHER_DOCUMENTS: 'OTHER_DOCUMENTS',
    GSTIN: 'GSTIN',
};

export const documentStatus = {
    PENDING: "PENDING",
    INREVIEW: "INREVIEW",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
};

export const documentStatusName = {
    [documentStatus.PENDING]: 'Not Verified',
    [documentStatus.INREVIEW]: 'In Review',
    [documentStatus.ACCEPTED]: 'Verified',
    [documentStatus.REJECTED]: 'Rejected',
};

export const COMPANY_TYPE = {
    ALL: 1,
    DEBTOR: 2,
    CREDITOR: 3,
};

export const COMPANY_TYPE_TEXT = {
    ALL: 'Creditor & Debtor',
    DEBTOR: 'Debtor',
    CREDITOR: 'Creditor',
};

export const INVITATION_STATUS = {
    PENDING: 1,
    ACCEPTED: 2,
    DECLINED: 3,
};

export const INVITATION_STATUS_TEXT = {
    PENDING: 'Pending',
    ACCEPTED: 'Accepted',
    REJECTED: 'Rejected',
};

export const INVITATION_ACTIONS = {
    COMPANY_ADD_REQUEST_ACCEPT: 'COMPANY_ADD_REQUEST_ACCEPT',
    COMPANY_ADD_REQUEST_REJECT: 'COMPANY_ADD_REQUEST_REJECT',
    ADD_AS_AUTHORIZED_PERSON_REQUEST_ACCEPT: 'ADD_AS_AUTHORIZED_PERSON_REQUEST_ACCEPT',
    ADD_AS_AUTHORIZED_PERSON_REQUEST_REJECT: 'ADD_AS_AUTHORIZED_PERSON_REQUEST_REJECT',
    OWNERSHIP_TRANSFER_REQUEST_ACCEPT: 'OWNERSHIP_TRANSFER_REQUEST_ACCEPT',
    OWNERSHIP_TRANSFER_REQUEST_REJECT: 'OWNERSHIP_TRANSFER_REQUEST_REJECT',
    ADD_CREDIT_TRANSACTION_REQUEST_ACCEPT: 'ADD_CREDIT_TRANSACTION_REQUEST_ACCEPT',
    ADD_CREDIT_TRANSACTION_REQUEST_REJECT: 'ADD_CREDIT_TRANSACTION_REQUEST_REJECT',
};

export const WEB_SOCKET_EVENTS = {
    USER_CONNECTED: 'USER_CONNECTED',
    NOTIFICATIONS: 'NOTIFICATIONS',
    USER_LOGOUT: 'USER_LOGOUT',
};

export const NOTIFICATIONS_TYPE = {
    COMPANY_ADD_REQUEST: 'COMPANY_ADD_REQUEST',
    COMPANY_ADD_REQUEST_ACCEPT: 'COMPANY_ADD_REQUEST_ACCEPT',
    COMPANY_ADD_REQUEST_ACCEPT_SELF: 'COMPANY_ADD_REQUEST_ACCEPT_SELF',
    COMPANY_ADD_REQUEST_REJECT: 'COMPANY_ADD_REQUEST_REJECT',
    COMPANY_ADD_REQUEST_REJECT_SELF: 'COMPANY_ADD_REQUEST_REJECT_SELF',
    ADD_AS_AUTHORIZED_PERSON_REQUEST: 'ADD_AS_AUTHORIZED_PERSON_REQUEST',
    ADD_AS_AUTHORIZED_PERSON_REQUEST_ACCEPT: 'ADD_AS_AUTHORIZED_PERSON_REQUEST_ACCEPT',
    ADD_AS_AUTHORIZED_PERSON_REQUEST_ACCEPT_SELF: 'ADD_AS_AUTHORIZED_PERSON_REQUEST_ACCEPT_SELF',
    ADD_AS_AUTHORIZED_PERSON_REQUEST_REJECT: 'ADD_AS_AUTHORIZED_PERSON_REQUEST_REJECT',
    ADD_AS_AUTHORIZED_PERSON_REQUEST_REJECT_SELF: 'ADD_AS_AUTHORIZED_PERSON_REQUEST_REJECT_SELF',
    OWNERSHIP_TRANSFER_REQUEST: 'OWNERSHIP_TRANSFER_REQUEST',
    OWNERSHIP_TRANSFER_REQUEST_ACCEPT: 'OWNERSHIP_TRANSFER_REQUEST_ACCEPT',
    OWNERSHIP_TRANSFER_REQUEST_ACCEPT_SELF: 'OWNERSHIP_TRANSFER_REQUEST_ACCEPT_SELF',
    OWNERSHIP_TRANSFER_REQUEST_REJECT: 'OWNERSHIP_TRANSFER_REQUEST_REJECT',
    OWNERSHIP_TRANSFER_REQUEST_REJECT_SELF: 'OWNERSHIP_TRANSFER_REQUEST_REJECT_SELF',
    ADD_CREDIT_TRANSACTION_REQUEST: 'ADD_CREDIT_TRANSACTION_REQUEST',
    ADD_CREDIT_TRANSACTION_REQUEST_ACCEPT: 'ADD_CREDIT_TRANSACTION_REQUEST_ACCEPT',
    ADD_CREDIT_TRANSACTION_REQUEST_ACCEPT_SELF: 'ADD_CREDIT_TRANSACTION_REQUEST_ACCEPT_SELF',
    ADD_CREDIT_TRANSACTION_REQUEST_REJECT: 'ADD_CREDIT_TRANSACTION_REQUEST_REJECT',
    ADD_CREDIT_TRANSACTION_REQUEST_REJECT_SELF: 'ADD_CREDIT_TRANSACTION_REQUEST_REJECT_SELF',
    CREDIT_TRANSACTION_REMINDER: 'CREDIT_TRANSACTION_REMINDER',
    BEFORE_OVERDUE_TRANSACTION_REMINDER: 'BEFORE_OVERDUE_TRANSACTION_REMINDER',
    AFTER_OVERDUE_TRANSACTION_REMINDER: 'AFTER_OVERDUE_TRANSACTION_REMINDER',
    CRITICAL_DUE_TRANSACTION_WARNING: 'CRITICAL_DUE_TRANSACTION_WARNING',
    CRITICAL_DUE_TRANSACTION_WARNING_SELF: 'CRITICAL_DUE_TRANSACTION_WARNING_SELF',
    CRITICAL_DUE_COMPANY_WARNING: 'CRITICAL_DUE_COMPANY_WARNING',
    CRITICAL_DUE_COMPANY_WARNING_SELF: 'CRITICAL_DUE_COMPANY_WARNING_SELF',
    TRANSACTION_CHALLENGED: 'TRANSACTION_CHALLENGED',
    TRANSACTION_CHALLENGED_SELF: 'TRANSACTION_CHALLENGED_SELF',
    TRANSACTION_ISSUED: 'TRANSACTION_ISSUED',
    TRANSACTION_IN_COURT: 'TRANSACTION_IN_COURT',
    VERIFICATION_ADDRESS_NOT_MATCHED_COMPANY: 'VERIFICATION_ADDRESS_NOT_MATCHED_COMPANY',
    VERIFICATION_ADDRESS_NOT_MATCHED_INDIVIDUAL: 'VERIFICATION_ADDRESS_NOT_MATCHED_INDIVIDUAL',
    INDIVIDUAL_DOCUMENT_REJECTED: 'INDIVIDUAL_DOCUMENT_REJECTED',
    COMPANY_DOCUMENT_REJECTED: 'COMPANY_DOCUMENT_REJECTED',
    INDIVIDUAL_DOCUMENT_VERIFICATION_COMPLETE: 'INDIVIDUAL_DOCUMENT_VERIFICATION_COMPLETE',
    COMPANY_DOCUMENT_VERIFICATION_COMPLETE: 'COMPANY_DOCUMENT_VERIFICATION_COMPLETE',
    SEND_PAYMENT_BY_DEBTOR: 'SEND_PAYMENT_BY_DEBTOR',
    GOODS_RETURN_BY_CREDITOR: 'GOODS_RETURN_BY_CREDITOR',
    DEACTIVATE_AS_AUTHORIZED_PERSON: 'DEACTIVATE_AS_AUTHORIZED_PERSON',
    REJECT_SENT_PAYMENT_BY_DEBTOR: 'REJECT_SENT_PAYMENT_BY_DEBTOR',
    RECEIVE_PAYMENT_BY_CREDITOR: 'RECEIVE_PAYMENT_BY_CREDITOR',
    RECEIVE_PAYMENTS_MULTIPAL_BY_CREDITOR: 'RECEIVE_PAYMENTS_MULTIPAL_BY_CREDITOR',
    INDIVIDUAL_NAME_REJECTED: 'INDIVIDUAL_NAME_REJECTED',
    COMPANY_NAME_REJECTED: 'COMPANY_NAME_REJECTED',
    INCREASE_TRANSACTION_CREDIT_LIMIT: 'INCREASE_TRANSACTION_CREDIT_LIMIT',
    TRANSACTION_COMPLETED: 'TRANSACTION_COMPLETED',
    NOTIFY_REMAINING_OVERDUE_AMOUNTS_DEBTOR: 'NOTIFY_REMAINING_OVERDUE_AMOUNTS_DEBTOR',
    NOTIFY_REMAINING_OVERDUE_AMOUNTS_CREDITOR: 'NOTIFY_REMAINING_OVERDUE_AMOUNTS_CREDITOR',
    GST_REGISTERED_DATE_REJECTED: 'GST_REGISTERED_DATE_REJECTED',
    UPDATE_AS_AUTHORIZED_PERSON: 'UPDATE_AS_AUTHORIZED_PERSON',

    SELLER_INIT_BUYER_FORM_RESPONSE: 'SELLER_INIT_BUYER_FORM_RESPONSE',
    SELLER_INIT_BUYER_APPROVED_RESPONSE: 'SELLER_INIT_BUYER_APPROVED_RESPONSE',
    SELLER_INIT_APPROVED: 'SELLER_INIT_APPROVED',
    BUYER_INIT_SELLER_APPROVED_RESPONSE: 'BUYER_INIT_SELLER_APPROVED_RESPONSE',
    BUYER_INIT_SELLER_FORM_RESPONSE: 'BUYER_INIT_SELLER_FORM_RESPONSE',
    BUYER_INIT_APPROVED: 'BUYER_INIT_APPROVED',


};

export const YES = 1;
export const NO = 0;
export const TRUE = 1;
export const FALSE = 0;

export const LocalStateCode = '26';
export const LocalPinCodeArray = [
    '362520',
    '362540',
    '362570',
    '396210',
    '396215',
    '396220',
];


export const COMPANY_ROLES = {
    OWNER: 'OWNER',
    AUTHORIZED_USER: 'AUTHORIZED_USER',
};

export const COMPANY_SEARCH = {
    GSTIN: 'GSTIN',
    GST: 'GST',
    PAN: 'PAN',
    RI: 'RI',
    REPUTE_ID: 'REPUTE ID',
    MCA: 'MCA',

}

export const TRANSACTION_STATUS = {
    ALL: 0,
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    OVERDUE: "OVERDUE",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    IN_COURT: "IN_COURT",
    CRITICAL_DUE: "CRITICAL_DUE",
    CRITICALDUE: "CRITICALDUE",
    ISSUE: "ISSUE",
    BAD_DEBT: "BAD_DEBT",
    BADDEBT: "BADDEBT",
    DELETED: "DELETED",
    DRAFT: "DRAFT",
    BIN: "BIN",
};


export const LEDNER_TRANSACTION_STATUS = {
    ALL: 0,
    DRAFT: "DRAFT",
    ON_GOING: "ON_GOING",
    COMPLETED: "COMPLETED",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    PENDING: "PENDING",
    OVERDUE: "OVERDUE",

    DUE: "DUE",
    CRITICAL_DUE: "CRITICAL_DUE",
    CRITICALDUE: "CRITICALDUE",
    NO_DUE: "NO_DUE"
};

export const SETTLEMENT_AGREEMNET_STATUS = {
    ALL: 0,
    DRAFT: "DRAFT",
    COMPLETED: "COMPLETED",
    PENDING: "PENDING",
};


export const TRANSACTION_STATUS_TEXT = {
    PENDING: 'Pending',
    ACCEPTED: 'Current', // current transaction
    REJECTED: 'Rejected',
    DECLINED: 'Declined',
    OVERDUE: 'Overdue',
    BAD_DEBT: 'Critical Due',
    BLACKLISTED: 'Blacklisted',
    ISSUE: 'Bad Debt',
    INCOURT: 'In court',
    COMPLETED: 'Completed',
    DELETED: 'Deleted',
};

export const TIMELINE_EVENT = {
    CREATED: 'CREATED',
    UPDATED: 'UPDATED',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    CREDIT_LIMIT_UPDATED: 'CREDIT_LIMIT_UPDATED',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    DELETED: 'DELETED',
    PUBLISHED: 'PUBLISHED',
    UNPUBLISHED: 'UNPUBLISHED',
    COMPLETED: 'COMPLETED',
    OVERDUE: 'OVERDUE',
    REMINDER_SENDED: 'REMINDER_SENDED',
    CURRENT: 'CURRENT',
    BAD_DEBT: 'BAD_DEBT',
    CRITICAL_DUE: 'CRITICAL_DUE',
    ISSUED: 'ISSUED',
    TAKEN_TO_COURT: 'TAKEN_TO_COURT',
    SEND_PAYMENT: 'SEND_PAYMENT',
    RECEIVE_PAYMENT: 'RECEIVE_PAYMENT',
    GOODS_RETURN: 'GOODS_RETURN',
    CREDIT_NOTE: 'CREDIT_NOTE',
};



export const USER_PERMISSIONS = {
    VIEW_ALL_COMPANY: 'VIEW_ALL_COMPANY',
    ADD_NEW_COMPANY: 'ADD_NEW_COMPANY',
    DOCUMENTS: 'DOCUMENTS',
    PROFILES: 'PROFILES',
    NOTIFICATIONS: 'NOTIFICATIONS',
    GUEST: 'GUEST',
    GROUPS: 'GROUPS',
};

export const COMPANY_PERMISSIONS = {
    DASHBOARD: 'DASHBOARD',
    COMPANY_SEARCH: 'COMPANY_SEARCH',
    INDIVIDUAL_SEARCH: 'INDIVIDUAL_SEARCH',
    DEBTORS: 'DEBTORS',
    CREDITORS: 'CREDITORS',
    AUTHORIZED_PERSONS: 'AUTHORIZED_PERSONS',
    RECEIVE_PAYMENT: 'RECEIVE_PAYMENT',
    GOODS_RETURN: 'GOODS_RETURN',
    CREDIT_NOTE: 'CREDIT_NOTE',
    SEND_PAYMENT: 'SEND_PAYMENT',
    AGREEMENT_SETTLEMENT: 'AGREEMENT_SETTLEMENT',
    SEND_BILL_TRANSACTION: 'SEND_BILL_TRANSACTION',

    BUYER_INITIATED_TRANSACTION: 'BUYER_INITIATED_TRANSACTION',
    SELLER_INITIATED_TRANSACTION: 'SELLER_INITIATED_TRANSACTION',
    LENDER_INITIATED_TRANSACTION: 'LENDER_INITIATED_TRANSACTION',

    DEBIT_SELL: 'DEBIT_SELL',
    DEBIT_SELL_PENDING: 'DEBIT_SELL_PENDING',
    DEBIT_SELL_CURRENT: 'DEBIT_SELL_CURRENT',
    DEBIT_SELL_OVERDUE: 'DEBIT_SELL_OVERDUE',
    DEBIT_SELL_BEDDEBT: 'DEBIT_SELL_BEDDEBT',
    DEBIT_SELL_ISSUES: 'DEBIT_SELL_ISSUES',
    DEBIT_SELL_INCOURT: 'DEBIT_SELL_INCOURT',
    DEBIT_SELL_COMPLETE: 'DEBIT_SELL_COMPLETE',
    DEBIT_SELL_BIN: 'DEBIT_SELL_BIN',
    CREDIT_BUY: 'CREDIT_BUY',
    CREDIT_BUY_PENDING: 'CREDIT_BUY_PENDING',
    CREDIT_BUY_CURRENT: 'CREDIT_BUY_CURRENT',
    CREDIT_BUY_OVERDUE: 'CREDIT_BUY_OVERDUE',
    CREDIT_BUY_BEDDEBT: 'CREDIT_BUY_BEDDEBT',
    CREDIT_BUY_ISSUES: 'CREDIT_BUY_ISSUES',
    CREDIT_BUY_INCOURT: 'CREDIT_BUY_INCOURT',
    CREDIT_BUY_COMPLETE: 'CREDIT_BUY_COMPLETE',
    CREDIT_BUY_BIN: 'CREDIT_BUY_BIN',
    DEPARTMENTS: 'DEPARTMENTS',
    DOCUMENTS: 'DOCUMENTS',
    PROFILES: 'PROFILES',
    BILLING: 'BILLING',
    SMS: 'SMS',
    REPORTS: 'REPORTS',
    RECEIVE: 'RECEIVE',
    QUOTES: 'QUOTES',
    REQUIREMENTS: 'REQUIREMENTS',
    BEDDEBTACCOUNT: "BEDDEBTACCOUNT",
    BALANCELOGS: "BALANCELOGS",
    CRITICAL_DUE: "CRITICAL_DUE",

    // MARKETING PERMISSIONS
    MARKETING: 'MARKETING',
    CUSTOMERS: "CUSTOMERS",
    LEADS: "LEADS",
    PRODUCTS: 'PRODUCTS',
    MARKETING_SETTINGS: 'MARKETING_SETTINGS',

};

export const ADMIN_PERMISSIONS = {

    ADMIN_DASHBOARD: "ADMIN_DASHBOARD",
    ADMIN_CWR: "ADMIN_CWR",
    ADMIN_LCR: "ADMIN_LCR",
    ADMIN_RECOVER_BADDEBT_BY_LF: "ADMIN_RECOVER_BADDEBT_BY_LF",
    ADMIN_LEGAL_NOTICES: "ADMIN_LEGAL_NOTICES",
    ADMIN_WSL_CONTACT_US: "ADMIN_WSL_CONTACT_US",
    ADMIN_LEGAN_CONTACT_US: "ADMIN_LEGAN_CONTACT_US",
    ADMIN_LEGAN_FEEDBACK: "ADMIN_LEGAN_FEEDBACK",
    USERS: "USERS",
    COMPANIES: "COMPANIES",
    USERS_EDIT: "USERS_EDIT",
    COMPANIES_EDIT: "COMPANIES_EDIT",
    BALANACE_USAGE_LIST: "BALANACE_USAGE_LIST",
    CRM: 'CRM',
    LEGAL_DOCUMENTATION_SERVICE: "LEGAL_DOCUMENTATION_SERVICE",
    CREDIT_SCORE_REPORTS: "CREDIT_SCORE_REPORTS",
    SKIP_TRACING_REPORTS: "SKIP_TRACING_REPORTS",
    AML_COURT_CASE: "AML_COURT_CASE",
    CAT: "CAT",
 // ServiceRequest types permissions
    SERVICE_REQUESTS: "SERVICE_REQUESTS",
    AML_SANCTIONS_SCREENING: "AML_SANCTIONS_SCREENING",
    BANK_DEFAULTERS: "BANK_DEFAULTERS",
    CREDIT_RATINGS: "CREDIT_RATINGS",
    DETAILED_FINANCIALS: "DETAILED_FINANCIALS",
    FIR_DETAILS: "FIR_DETAILS",
    LITIGATIONS_BI: "LITIGATIONS_BI",
    MCA_CHARGES: "MCA_CHARGES",
    UDYAM_ADVANCED: "UDYAM_ADVANCED",
    IEC_TRANSACTIONS: "IEC_TRANSACTIONS",
    IEC_PROFILE: "IEC_PROFILE",
    ALERTS: "ALERTS",
    ENTITY_SEARCH: "ENTITY_SEARCH",
    DIRECTOR_DETAILS: "DIRECTOR_DETAILS",
    RELATED_PARTIES: "RELATED_PARTIES",



    BALANCE_RECHARGES : 'BALANCE_RECHARGES',
    SUBSCRIPTIONS:'SUBSCRIPTIONS',

    PROMO_MAILS: "PROMO_MAILS",
    MARKETING_CONTACTS: "MARKETING_CONTACTS",
    MARKETING_CAMPAIGNS: "MARKETING_CAMPAIGNS",

    ANALYTICS_COST: "ANALYTICS_COST",
    ANALYTICS_VOICE: "ANALYTICS_VOICE",
    ANALYTICS_PLATFORM_USAGE: "ANALYTICS_PLATFORM_USAGE",
    ANALYTICS_PLATFORM_REGISTRATION: "ANALYTICS_PLATFORM_REGISTRATION",
    ANALYTICS_SUBSCRIPTION: "ANALYTICS_SUBSCRIPTION",
    SERVICES_CREDIT:"SERVICES_CREDIT",

    BALANCE_SETTING: "BALANCE_SETTING",
    SUBSCRIPTION_PLANS: "SUBSCRIPTION_PLANS",
    FEATURES_GROUPS: "FEATURES_GROUPS",
    SERVICE_NOTIFICATION: "SERVICE_NOTIFICATION",

    //logs 
    ACTIVITY_LOGS: "ACTIVITY_LOGS",
    LOGIN_LOGS: "LOGIN_LOGS",
    MANUAL_PAYMENTS:"MANUAL_PAYMENTS" ,
    MCA_SCHEDULES:"MCA_SCHEDULES"
}


export const SEND_PAYMENT_METHOD = {
    CASH: '1',
    CHEQUE: '2',
    NEFT_RTGS_IMPS: '3',
    OTHERS: '4',
    GOODS_RETURN: '5',
    CREDIT_NOTE: '6',
};

export const RECEIVE_PAYMENT_STATUS = {
    PENDING: '1',
    ACCEPT: '2',
    DECLINED: '3',
};
export const COMPLETE_TRANSACTION_REASON = {
    'DISCOUNT': '1',
    'SETTLEMENT': '2',
    'OTHERS': '3',
};

export const BAD_DEBT_TRANSACTION_REASON = {
    'PAYMENT_PROBLEM': '1',
    'BUYER_PROBLEM': '2',
    'OTHERS': '3',
};

export const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR'
}

export const profileStatus = {
    Pending: 'Pending',
    Approved: 'Approved',
    Rejected: 'Rejected',
    In_review: 'In review',
}


export const lenderEmiPeriods = {
    WEEKLY: 'WEEKLY',
    HALF_MONTHLY: 'HALF_MONTHLY',
    MONTHLY: 'MONTHLY',
    QUARTERLY: 'QUARTERLY',
    HALF_YEARLY: 'HALF_YEARLY',
    YEARLY: 'YEARLY'
}

export const SELLER_BUYER_STAGES = {

    SELLER_INIT_DRAFT: 'SELLER_INIT_DRAFT',
    SELLER_INIT_BUYER_FORM: 'SELLER_INIT_BUYER_FORM',
    SELLER_INIT_BUYER_DECLINED: 'SELLER_INIT_BUYER_DECLINED',
    SELLER_INIT_BUYER_APPROVED: 'SELLER_INIT_BUYER_APPROVED',
    SELLER_INIT_APPROVED: 'SELLER_INIT_APPROVED',
    SELLER_INIT_DECLINED: 'SELLER_INIT_DECLINED',

    BUYER_INIT_DRAFT: 'BUYER_INIT_DRAFT',
    BUYER_INIT_SELLER_FORM: 'BUYER_INIT_SELLER_FORM',
    BUYER_INIT_SELLER_DECLINED: 'BUYER_INIT_SELLER_DECLINED',
    BUYER_INIT_SELLER_APPROVED: 'BUYER_INIT_SELLER_APPROVED',
    BUYER_INIT_APPROVED: 'BUYER_INIT_APPROVED',
    BUYER_INIT_DECLINED: 'BUYER_INIT_DECLINED'
}




export const GUIDE_SECTIONS = {
    DASHBOARD: "DASHBOARD"
}

export const ALERT_ACTIONS_CARD = {
    DIGITAL_FOLLOWUP_ALERT: "DIGITAL_FOLLOWUP_ALERT",
    CALL_ALL_TIME_ALERT: "CALL_ALL_TIME_ALERT",
    LEGAL_NOTICE_ALERT: "LEGAL_NOTICE_ALERT",
    TAKE_LEGAL_ACTION_ALERT: "TAKE_LEGAL_ACTION_ALERT"

};



export const CRM_TYPES = {

    LEGAL_CREDIBILITY: 'LEGAL_CREDIBILITY',
    RISK_EVALUATION: 'RISK_EVALUATION',
    LEGAL_NOTICE: 'LEGAL_NOTICE',
    RECOVER_BAD_DEBTS: 'RECOVER_BAD_DEBTS',
    LEGAL_DOCUMENTATION: 'LEGAL_DOCUMENTATION'
}